2021-04-30 11:24:26,388 INFO     ---------------------------------------------------------------------------------------------
2021-04-30 11:24:26,393 INFO     Geo: cqd
2021-04-30 11:24:26,394 INFO     Data Path: data/NELL-betae
2021-04-30 11:24:26,394 INFO     #entity: 63361
2021-04-30 11:24:26,394 INFO     #relation: 400
2021-04-30 11:24:26,394 INFO     #max steps: 1000
2021-04-30 11:24:26,394 INFO     Evaluate unoins using: DNF
2021-04-30 11:24:26,394 INFO     loading data
2021-04-30 11:24:50,153 INFO     Training info:
2021-04-30 11:24:50,168 INFO     Validation info:
2021-04-30 11:24:50,169 INFO     3p: 4000
2021-04-30 11:24:50,171 INFO     Test info:
2021-04-30 11:24:50,171 INFO     3p: 4000
2021-04-30 11:24:51,701 INFO     Model Parameter Configuration:
2021-04-30 11:24:51,701 INFO     Parameter embeddings.0.weight: torch.Size([63361, 2000]), require_grad = True
2021-04-30 11:24:51,702 INFO     Parameter embeddings.1.weight: torch.Size([400, 2000]), require_grad = True
2021-04-30 11:24:51,702 INFO     Parameter Number: 127522000
2021-04-30 11:24:58,427 INFO     Loading checkpoint models/nell-betae...
2021-04-30 11:25:00,461 INFO     tasks = 3p
2021-04-30 11:25:00,461 INFO     init_step = 99999
2021-04-30 11:25:00,461 INFO     batch_size = 1000
2021-04-30 11:25:00,461 INFO     hidden_dim = 1000
2021-04-30 11:25:00,461 INFO     gamma = 12.000000
2021-04-30 11:25:00,461 INFO     Evaluating on Valid Dataset...
  0%|          | 0/4000 [00:00<?, ?it/s]2021-04-30 11:25:00,705 INFO     Evaluating the model... (0/4000)
  0%|          | 1/4000 [00:00<16:03,  4.15it/s]
main.py --do_valid --do_test --data_path data/NELL-betae -n 1 -b 1000 -d 1000 -lr 0.1 --disable_warmup --max_steps 1000 --cpu_num 0 --geo cqd --valid_steps 20 --tasks 3p --print_on_screen --test_batch_size 1 --optimizer Adagrad --reg_weight 0.05 --log_steps 5 --checkpoint_path models/nell-betae --cqd d2 --cqd-t-norm min --cqd-k 64 --no-save --cuda
overwritting args.save_path
logging to models/nell-betae
99999
Traceback (most recent call last):
  File "main.py", line 508, in <module>
    main(parse_args())
  File "main.py", line 497, in main
    valid_all_metrics = evaluate(model, valid_easy_answers, valid_hard_answers, args, valid_dataloader, query_name_dict, 'Valid', step, writer)
  File "main.py", line 165, in evaluate
    metrics = KGReasoning.test_step(model, tp_answers, fn_answers, args, dataloader, query_name_dict)
  File "/home/pminervi/workspace/KGReasoning/models.py", line 654, in test_step
    _, negative_logit, _, idxs = model(None, negative_sample, None, batch_queries_dict, batch_idxs_dict)
  File "/home/pminervi/anaconda3/envs/gpu/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pminervi/workspace/KGReasoning/cqd.py", line 356, in forward
    k=self.k, t_norm=t_norm)
  File "/home/pminervi/workspace/KGReasoning/d2.py", line 147, in query_3p
    scoring_function=scoring_function)
  File "/home/pminervi/workspace/KGReasoning/d2.py", line 32, in score_candidates
    atom_scores_2d = scoring_function(s_emb, p_emb, candidates_emb)
  File "/home/pminervi/workspace/KGReasoning/cqd.py", line 333, in scoring_function
    res, _ = self.score_o(lhs_, rel_, rhs_)
  File "/home/pminervi/workspace/KGReasoning/cqd.py", line 114, in score_o
    return score_1 + score_2, factors
RuntimeError: CUDA out of memory. Tried to allocate 992.00 MiB (GPU 0; 10.76 GiB total capacity; 7.89 GiB already allocated; 891.44 MiB free; 8.79 GiB reserved in total by PyTorch)
